/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodelgato;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.Thread.sleep;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gateway
 */
public class VentanaJuego extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form VentanaJuego
     */
  
    private int ganador; //1 para jugador x, 2 para jugador O y 3 para jugador gato
    private boolean jugador;
    private boolean valor;
    Thread checador;
    
    private Socket chatClient;
    
    private OutputStream outputStream;
    private InputStream inputStream;
    
    private DataOutputStream salidaDatos;
    private DataInputStream entradaDatos;
    
    private Thread recibir;
    
    
    public VentanaJuego(String jugadorUno) {
        initComponents();
       
        this.ganador = 0;
        this.jugador = true;
        this.valor = true;
        conexion(8080,"localhost");
                        
        txtGato.setText("0");
        txtJugadorO.setText("0");
        txtJugadorX.setText("0");
        
        this.lblJugadorUno.setText(jugadorUno);        
        reiniciar();
        this.checador = new Thread(this);
        this.checador.start();
        
        
        
        
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btIniciarJuego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblJugadorUno = new javax.swing.JLabel();
        txtJugadorX = new javax.swing.JTextField();
        lblJugadorDos = new javax.swing.JLabel();
        txtJugadorO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGato = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnTerminarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gato");

        btIniciarJuego.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btIniciarJuego.setText("IniciarJuego");
        btIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarJuegoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Marcadores");

        lblJugadorUno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblJugadorUno.setText("Jugador ( X )");

        txtJugadorX.setEditable(false);

        lblJugadorDos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblJugadorDos.setText("Jugador ( O )");

        txtJugadorO.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Gato");

        txtGato.setEditable(false);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnTerminarJuego.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTerminarJuego.setText("Terminar Juego");
        btnTerminarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblJugadorUno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtJugadorX, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(lblJugadorDos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtJugadorO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGato, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btIniciarJuego)
                        .addGap(30, 30, 30)
                        .addComponent(btnTerminarJuego)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTerminarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorUno)
                    .addComponent(txtJugadorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugadorDos)
                    .addComponent(txtJugadorO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarJuegoActionPerformed
        reiniciar();
    }//GEN-LAST:event_btIniciarJuegoActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        this.btn1.setText(colocarEnCasilla(checaPulsos()));
        this.btn1.setEnabled(false);
        this.valor = true;
        enviarDatos("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.btn2.setText(colocarEnCasilla(checaPulsos()));
        this.btn2.setEnabled(false);
                this.valor = true;

        enviarDatos("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        
        this.btn3.setText(colocarEnCasilla(checaPulsos()));
        this.btn3.setEnabled(false);
        this.valor = true;
        enviarDatos("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        
        this.btn4.setText(colocarEnCasilla(checaPulsos()));
        this.btn4.setEnabled(false);
        this.valor = true;
        enviarDatos("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        
        this.btn5.setText(colocarEnCasilla(checaPulsos()));
        this.btn5.setEnabled(false);
        this.valor = true;
        enviarDatos("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        
        this.btn6.setText(colocarEnCasilla(checaPulsos()));
        this.btn6.setEnabled(false);
        this.valor = true;
        
        enviarDatos("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        
        this.btn7.setText(colocarEnCasilla(checaPulsos()));
        this.btn7.setEnabled(false);
        this.valor = true;
        
        enviarDatos("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        
        this.btn8.setText(colocarEnCasilla(checaPulsos()));
        this.btn8.setEnabled(false);
        this.valor = true;
        
        enviarDatos("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        
        this.btn9.setText(colocarEnCasilla(checaPulsos()));
        this.btn9.setEnabled(false);
        this.valor = true;
        
        enviarDatos("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnTerminarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarJuegoActionPerformed
        this.valor = true;
        terminarJuego();
        
    }//GEN-LAST:event_btnTerminarJuegoActionPerformed
    
    //establecer la conexion
    public void conexion(int puerto, String ip){
        try{
            this.chatClient = new Socket(ip,puerto); 
            enviarDatos();
            //this.recibir.start();            
        }catch(IOException e){
            messagesInformation(e.toString(),JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void enviarDatos(String mensaje){
        //this.txtMensajesRecibidos.append(this.MSG_SEND+mensaje+"\n");
        try{
            this.outputStream = this.chatClient.getOutputStream();
            this.salidaDatos = new DataOutputStream(this.outputStream);
            
            this.salidaDatos.writeUTF("MSG:"+mensaje);
            this.salidaDatos.flush();
        }catch(IOException e){
            messagesInformation(e.toString(),JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void enviarDatos(){        
        try{
            this.outputStream = this.chatClient.getOutputStream();
            this.salidaDatos = new DataOutputStream(this.outputStream);
            
            this.salidaDatos.writeUTF("USER:"+this.lblJugadorUno.getText());
            this.salidaDatos.flush();
        }catch(IOException e){
            messagesInformation(e.toString(),JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void recibirDatos(){        
        try{
            this.inputStream = this.chatClient.getInputStream();
            this.entradaDatos = new DataInputStream(this.inputStream);
            
            String dato = this.entradaDatos.readUTF();
            System.out.println(dato);
            determinarJugada(dato);
        }catch(IOException e){
            messagesInformation(e.toString(),JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void determinarJugada(String jugada){
        String datos[] = jugada.split(":");
                
        
        if(datos[0].equals(this.lblJugadorUno.getText())){
        
        }else{
            
            this.valor = false;
            if (datos[1].equals("1")){
                
                this.btn1.doClick();

            }else if (datos[1].equals("2")){                
                this.btn2.doClick();

            }else if (datos[1].equals("3")){               
                this.btn3.doClick();
            }else if (datos[1].equals("4")){               
               this.btn4.doClick();
            }else if (datos[1].equals("5")){               
                this.btn5.doClick();
            }else if (datos[1].equals("6")){
                this.btn6.doClick();
            }else if (datos[1].equals("7")){
                this.btn7.doClick();
            }else if (datos[1].equals("8")){
                this.btn8.doClick();
            }else if (datos[1].equals("9")){
                this.btn9.doClick();
            }
        }
    }
    
    private void messagesInformation(String message,int typeMessage){
        JOptionPane.showMessageDialog(null, message,"Java Chat",typeMessage);
    }
    
    private void terminarJuego(){
        if(JOptionPane.showConfirmDialog(null,"¿Desea terminar el juego?","Juego del Gato",JOptionPane.QUESTION_MESSAGE)==0){
            mensaje("Puntuaciones:\n "+lblJugadorUno.getText()+": "+txtJugadorX.getText()+"\n"+lblJugadorUno.getText()+": "+txtJugadorO.getText());
            reiniciar();
        }
    }
    private boolean checaPulsos(){
        if (this.jugador == true){
            this.jugador = false;
            return true;            
        }else{
            this.jugador = true;
            return false;
        }
    }
    
    private String colocarEnCasilla(boolean v){
        if (this.valor == true){
            return "X";
        }else{
            return "O";
        }
    }
    
    private void reiniciar(){
        this.btn1.setText("");
        this.btn2.setText("");
        this.btn3.setText("");
        this.btn4.setText("");
        this.btn5.setText("");
        this.btn6.setText("");
        this.btn7.setText("");
        this.btn8.setText("");
        this.btn9.setText("");
        
        this.ganador = 0;  
        
        this.jugador = true;
        
        this.btn1.setEnabled(true);
        this.btn2.setEnabled(true);
        this.btn3.setEnabled(true);
        this.btn4.setEnabled(true);
        this.btn5.setEnabled(true);
        this.btn6.setEnabled(true);
        this.btn7.setEnabled(true);
        this.btn8.setEnabled(true);
        this.btn9.setEnabled(true);
        
    }
    
    private void verificar(){
        
        //diagonal para jugador X
        
        if(btn1.getText().equals("X") & btn5.getText().equals("X") & btn9.getText().equals("X")){
            this.ganador = 1;            
        }
        
        if(btn3.getText().equals("X") & btn5.getText().equals("X") & btn7.getText().equals("X")){
            this.ganador = 1;            
        }
        
        //diagonal para jugador O
        
        if(btn1.getText().equals("O") & btn5.getText().equals("O") & btn9.getText().equals("O")){
            this.ganador = 2;            
        }
        
        if(btn3.getText().equals("O") & btn5.getText().equals("O") & btn7.getText().equals("O")){
            this.ganador = 2;            
        }
        
        //JUGADOR X
        if(btn1.getText().equals("X") & btn2.getText().equals("X") & btn3.getText().equals("X")){
            this.ganador = 1;            
        }
        
        if(btn4.getText().equals("X") & btn5.getText().equals("X") & btn6.getText().equals("X")){
            this.ganador = 1;            
        }
        
        if(btn7.getText().equals("X") & btn8.getText().equals("X") & btn9.getText().equals("X")){
            this.ganador = 1;            
        }
        
        //JUGADOR O
        if(btn1.getText().equals("O") & btn2.getText().equals("O") & btn3.getText().equals("O")){
            this.ganador = 2;            
        }
        
        if(btn4.getText().equals("O") & btn5.getText().equals("O") & btn6.getText().equals("O")){
            this.ganador = 2;            
        }
        
        if(btn7.getText().equals("O") & btn8.getText().equals("O") & btn9.getText().equals("O")){
            this.ganador = 2;            
        }
        
        //JUGADOR X
        if(btn1.getText().equals("X") & btn4.getText().equals("X") & btn7.getText().equals("X")){
            this.ganador = 1;            
        }
        
        if(btn2.getText().equals("X") & btn5.getText().equals("X") & btn8.getText().equals("X")){
            this.ganador = 1;            
        }
        
        if(btn3.getText().equals("X") & btn6.getText().equals("X") & btn9.getText().equals("X")){
            this.ganador = 1;            
        }
        
        //JUGADOR O
        //JUGADOR O
        if(btn1.getText().equals("O") & btn4.getText().equals("O") & btn7.getText().equals("O")){
            this.ganador = 2;            
        }
        
        if(btn2.getText().equals("O") & btn5.getText().equals("O") & btn8.getText().equals("O")){
            this.ganador = 2;            
        }
        
        if(btn3.getText().equals("O") & btn6.getText().equals("O") & btn9.getText().equals("O")){
            this.ganador = 2;            
        }
        
        
        
        
    }
    
    private boolean ganador(int jugador){
        if(jugador ==1){
            return true;
        }else if(jugador==2){
            return true;
        }else if(jugador==3){
            return true;            
        }else{
            return false;
        }                        
    }
    
    public static void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje,"Juego del Gato",JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    
    private void terminoJuego(boolean termino){
        String mensaje="";
        
        if(termino){
            
            if(this.ganador ==1){
                mensaje ="El ganador es el jugador X";
                txtJugadorX.setText(String.valueOf(Integer.parseInt(this.txtJugadorX.getText())+1));
            }
            
            if(this.ganador == 2){
                mensaje = "El ganador es el jugador O";
                txtJugadorO.setText(String.valueOf(Integer.parseInt(this.txtJugadorO.getText())+1));
            }
            
            if(this.ganador == 3){
                mensaje = "El ganador es el GATO";
                txtGato.setText(String.valueOf(Integer.parseInt(this.txtGato.getText())+1));
            }
            
            mensaje(mensaje);
            
            reiniciar();
        }
    }
    
    private void verificarGato(){
        if((this.ganador !=2) & (this.ganador != 1) & (!btn1.getText().equals("")) & (!btn2.getText().equals("")) & (!btn3.getText().equals("")) & (!btn4.getText().equals("")) & (!btn5.getText().equals("")) & (!btn6.getText().equals("")) & (!btn7.getText().equals("")) & (!btn8.getText().equals("")) & (!btn9.getText().equals(""))){
            this.ganador = 3;
        }
    }
    
    @Override
    public void run() {
        while(true){            
                verificar();
                terminoJuego(ganador(this.ganador));
                verificarGato();
                recibirDatos();
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciarJuego;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnTerminarJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblJugadorDos;
    private javax.swing.JLabel lblJugadorUno;
    private javax.swing.JTextField txtGato;
    private javax.swing.JTextField txtJugadorO;
    private javax.swing.JTextField txtJugadorX;
    // End of variables declaration//GEN-END:variables

    
}
